### ISSUE TITLE
Asset description length not arbitrary?

### ISSUE THREAD

**Issue by droplister** [CounterpartyXCP/Documentation#91]
I would consider this very low priority...

Protocol Specification states, "Asset descriptions may be of arbitrary length." However, it appears, at least when using Counterwallet, that 40 bytes is the limit for a description.

I have seen discussion online about 80 bytes being possible, depending on OP_RETURN settings.

This page states: https://counterparty.io/docs/api/ 52 bytes is the max.

There are also asset descriptions in the wild like: https://res.indiesquare.me/json/A2106870093763980398.json which are 57 bytes.

Perhaps, this part of the documentation can be clarified by someone who knows more than I do.

This is specifically about the description in an issuance, and not an enhanced asset info description which is 2048 chars max.

**Comment by unsystemizer** [comment]
Notes:
1) Before 42 - https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/messages/issuance.py#L146
2) Later 52 - https://github.com/CounterpartyXCP/counterparty-lib/blob/master/counterpartylib/lib/messages/issuance.py#L187
3 Related issue: https://github.com/CounterpartyXCP/counterparty-lib/pull/857

**Comment by unsystemizer** [comment]
@rubensayshi @deweller what do you suggest with regard to this issue in terms of documentation changes?

**Comment by unsystemizer** [comment]
* The protocol spec doc has been updated. Now the implementation limit still isn't mentioned, but at least it's cleared there's 2 asset descriptions, and which is which (changed in  https://github.com/CounterpartyXCP/Documentation/commit/4a453e5ff517b25942dcbb5487c21781153388da). Since it's just an implementation limit, I think it's OK to say "unlimited" - the protocol won't stop you, but you'd have to modify your server to deal with it, while other servers would truncate descs > 2048 bytes long.
* The current implementation limit can be seen in https://github.com/CounterpartyXCP/counterblock/blob/master/counterblock/schemas/asset.schema.json#L9)
*  https://github.com/CounterpartyXCP/counterparty-lib/pull/857 was closed and the other "on blockchain" limit of 52 bytes hasn't changed.
